In [1]:
import numpy as np

# Descomposición de matrices

## Descomposición LU

- Consiste en descomponer una matriz cuadrada en una triangular inferior L y una triangular superior U. Para eso se triangula A y se despeja U tal que A=LU.

- Primero se encuentra U, a partir de: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj}l_{ik}$

- Después se encuentra L, a partir de: $l_{ij}= \frac{1}{u_{jj}}(a_{ij}-\sum_{k=1}^{j-1}u_{kj}l_{ik})$

In [8]:
def LU(A): 
    n = np.shape(A)[0]
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for i in range(n):
        for j in range(i-1):
            sum=0
            for k in range (j-1):
                sum+=L[i][k]*U[k][j]
            L[i][j]=(A[i][j]-sum)/U[j][j]
        L[i][i]=1
        for j in range(i-1,n):
            sum1=0
            for k in range(i-1):
                sum1+=L[i][k]*U[k][j]
            U[i][j] = A[i][j]-sum1
    return(L,U)





A= [[ 2 -2  1]
 [ 0  1  2]
 [ 5  3  1]]
L= [[1.  0.  0. ]
 [0.  1.  0. ]
 [2.5 0.  1. ]]
U= [[ 2.  -2.   1. ]
 [ 0.   1.   2. ]
 [ 0.   8.  -1.5]]
LU= [[ 2. -2.  1.]
 [ 0.  1.  2.]
 [ 5.  3.  1.]]


In [ ]:
# Ejemplo:

A = np.array([[2,-2,1],[0,1,2],[5,3,1]])      #Defino la matriz como un array

L,U = LU(A)                                   #Calculo las matrices LU
print('A=',A)
print('L=',L)
print('U=',U)
print('LU=',np.dot(L,U))                      #Chequeo que A=LU


## Descomposición QR, con Gram-Schmidt

- Consiste en descomponer una matriz no necesariamente cuadrada en una $Q$ ortonormal $(Q\cdot Q^{t}=I)$ y otra triangular superior.
- En el método de Gram-Schmidt, si $v_{i}$ son las columnas de $A, u_{1}=\frac{v_{1}}{||v_{1}||},u_{n}=\frac{v_{n}-\sum_{i=1}^{n-1}\left(v_{n}\cdot u_{i}\right)u_{i}}{||v_{n}-\sum_{i=1}^{n-1}\left(v_{n}\cdot u_{i}\right)u_{i}||}$.

In [5]:
import numpy as np

def normal(v):
    normal = v / np.linalg.norm(v)
    return(normal)

def gran_yo(A):
    if np.shape(A)[1]>np.shape(A)[0]:
        A = np.transpose(A)
    Q = np.array([normal(A[:,0])])    
    for i in range(1,np.shape(A)[1]):
        v = A[:,i]
        for j in range(0,i):
            v = v-np.dot(v,Q[j])*Q[j]
        u = normal(v)
        Q = np.append(Q,[u],axis=0)
    R = np.dot(Q,A)
    Q = np.transpose(Q)
    return(Q,R)

In [15]:
#Ejemplo

A = np.array([[2,-2,1],[0,1,2],[5,3,1]])      #Defino la matriz como un array

Q,R = gran_yo(A)

print('QR=',np.dot(Q,R))                                      #Chequeo que A = QR

print('q1*q2=',np.dot(Q[0],Q[1]))                             #Chequeo que las columnas de Q son ortogonales
print('q1*q3=',np.dot(Q[0],Q[2]))
print('q2*q3=',np.dot(Q[1],Q[2]))

print('q1*q1=',np.dot(Q[0],Q[0]))                             #Chequeo que las columnas de Q tengan norma 1
print('q1*q1=',np.dot(Q[1],Q[1]))
print('q1*q1=',np.dot(Q[2],Q[2]))

QR= [[ 2.00000000e+00 -2.00000000e+00  1.00000000e+00]
 [-1.33554269e-15  1.00000000e+00  2.00000000e+00]
 [ 5.00000000e+00  3.00000000e+00  1.00000000e+00]]
q1*q2= -1.1102230246251565e-16
q1*q3= 1.249000902703301e-16
q2*q3= -2.0816681711721685e-16
q1*q1= 0.9999999999999999
q1*q1= 0.9999999999999999
q1*q1= 1.0


## SVD

- Si $A\in R^{m\times n}$, los valores singulares de $A$ son la raíz de los autovalores de $A^t A$.
– Para $m\geq n$, una descomposición en valores singulares de $A_{m\times n}$ es $A=U\Sigma V^{t}$

con $U\in R^{m\times m},V\in R^{n\times n}$, ortogonales y $\Sigma\in R^{m\times n}$ diagonal de la forma 
$
\Sigma=\left(\begin{array}{cccc}
\sigma_{1} & 0 & \cdots & 0\\
0 & \sigma_{2} & \cdots & 0\\
\vdots &  &  & \sigma_{n}\\
0 & \cdots & \cdots & 0\\
\vdots &  &  & \vdots\\
0 & \cdots & \cdots & 0
\end{array}\right)
$

In [22]:
#Para esto uso directamente la versión de numpy
A = np.array([[1,2,3],[4,5,6]])

U,s,V = np.linalg.svd(A)
S = np.zeros((A.shape[0],A.shape[1]))
S[:len(s), :len(s)] = np.diag(s)

print('U*S*V=',np.dot(U,np.dot(S,V)))



U*S*V= [[1. 2. 3.]
 [4. 5. 6.]]
